spring:
  kafka:
    bootstrap-servers: my-cluster-kafka-external-bootstrap-kafka.apps-crc.testing:443
    security:
      protocol: SSL
    ssl:
      trust-store-location: "classpath:ca.p12"
      trust-store-password: bVgnmB5HWAFi
    consumer:
      group-id: group-id
      # default is `latest`, it is used only when there is no offset information (for example when consumer group was removed)
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

#logging:
#  level:
#    org.springframework.kafka: DEBUG