apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: true
        configuration:
          bootstrap:
            nodePort: 30080
          brokers:
            - broker: 0
              nodePort: 30081
              advertisedHost: localhost
              advertisedPort: 8081
            - broker: 1
              nodePort: 30082
              advertisedHost: localhost
              advertisedPort: 8082
            - broker: 2
              nodePort: 30083
              advertisedHost: localhost
              advertisedPort: 8083
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }