# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: prod
patches:
  - path: increase-kafka-replicas.yaml
  - path: increase-controller-replicas.yaml


