spring:
  kafka:
    # needed for the admin client to create the initial topics
    bootstrap-servers: localhost:19092
    streams:
      application-id: join-examples
      bootstrap-servers: localhost:19092
      properties:
        state.dir: /tmp/kafka-streams
        # Kafka Streams will commit "as soon as possible"
        # cache.max.bytes.buffering is deprecated and will be removed in the future
        statestore.cache.max.bytes: 0


topics:
  stream-to-table:
    input1:
      name: user-clicks
      partitions: 1
      replicas: 1
    input2:
      name: user-regions
      partitions: 1
      replicas: 1
    output:
      name: clicks-per-region
      partitions: 1
      replicas: 1
  stream-to-stream:
    window-size-in-seconds: 5
    input1:
      name: ad-impressions
      partitions: 1
      replicas: 1
    input2:
      name: ad-clicks
      partitions: 1
      replicas: 1
    output:
      name: ad-impressions-and-clicks
      partitions: 1
      replicas: 1


management:
  endpoints:
    web.exposure.include: "*"

logging:
  level:
    org.springframework.kafka: DEBUG

