apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.2.3
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9095
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: nginx
          bootstrap:
            # modify it according to value `minikube ip`
            host: bootstrap.192.168.205.14.nip.io
          brokers:
            - broker: 0
              # modify it according to value `minikube ip`
              host: broker-0.192.168.205.14.nip.io
            - broker: 1
              # modify it according to value `minikube ip`
              host: broker-1.192.168.205.14.nip.io
            - broker: 2
              # modify it according to value `minikube ip`
              host: broker-2.192.168.205.14.nip.io

    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: { }
    userOperator: { }
