all:
  vars:
    ansible_connection: docker
    ansible_user: root
    ansible_become: true
    jmxexporter_enabled: true

zookeeper:
  hosts:
    zk1.dev.confluent:

kafka_broker:
  hosts:
    kafka-0.dev.confluent:
    kafka-1.dev.confluent:
    kafka-2.dev.confluent:


