---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: debezium-source-connector
  namespace: confluent
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    topic.prefix: prefix
    database.hostname: ${file:/mnt/secrets/sqlcreds/sqlcreds.txt:hostname}
    database.dbname: ${file:/mnt/secrets/sqlcreds/sqlcreds.txt:dbname}
    # https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-decimal-handling-mode
    # decimal.handling.mode: string
    decimal.handling.mode: double
    # decimal.handling.mode: precise
    # https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-permissions
    database.user: ${file:/mnt/secrets/sqlcreds/sqlcreds.txt:user}
    database.password: ${file:/mnt/secrets/sqlcreds/sqlcreds.txt:password}
    plugin.name: pgoutput
