global:
  postgresql:
    auth:
      # https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
      postgresPassword: "secret"

primary:
  # Instructs the server to use logical decoding with the write-ahead log.
  extendedConfiguration: |-
    wal_level = logical