---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: perf-testing-topic
  namespace: confluent
spec:
  replicas: 1
  partitionCount: 3
  configs:
    # it is set to 2 by default
    min.insync.replicas: "1"
    cleanup.policy: "delete"
  kafkaClusterRef:
    name: kafka
    namespace: confluent