server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      properties:
        # wait 5 seconds for messages and then sent it out with one batch to Kafka
        linger.ms: 5000
    template:
      default-topic: messages
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer

