apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: example-keycloak-realm-import
  namespace: my-keycloak-operator
  labels:
    app: sso
spec:
  keycloakCRName: example-keycloak
  realm: {}
