apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  # modify the address range to your config (see README)
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.24.255.0-172.24.255.255