---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center-next-gen:2.3.2
    init: confluentinc/confluent-init-container:3.1.1
  dataVolumeCapacity: 10Gi
  dependencies:
    kafka:
      bootstrapEndpoint: http://kafka.confluent.svc.cluster.local:9071
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    connect:
      - name: connect
        url: http://connect.confluent.svc.cluster.local:8083
