apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-source-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.kafka.connect.datagen.DatagenConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    kafka.topic: my-topic
    quickstart: Stock_Trades
    max.interval: 1000
    iterations: 10000000

