apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    # https://docs.confluent.io/kafka-connectors/jdbc/current/sink-connector/sink_config_options.html
    connection.url: "jdbc:postgresql://my-postgresql:5432/postgres"
    connection.user: postgres
    connection.password: <TODO>
    auto.create: true
    auto.evolve: true
    insert.mode: upsert
    pk.mode:
    pk.fields:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    # value.converter: io.confluent.connect.avro.AvroConverter

