apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    # https://docs.confluent.io/kafka-connectors/jdbc/current/sink-connector/sink_config_options.html
    connection.url: "jdbc:postgresql://my-postgresql:5432/postgres"
    connection.user: postgres
    connection.password: ds1uUg9nbH
    topics: my-topic
    auto.create: true
    auto.evolve: true
    insert.mode: upsert
    pk.mode: record_value
    pk.fields: userid
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.apicurio.registry.url: http://apicurio-registry-service:8080
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.serde.avro.AvroKafkaSerializer
    value.converter.apicurio.registry.converter.deserializer: io.apicurio.registry.serde.avro.AvroKafkaDeserializer
    value.converter.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
