server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'

#spring:
#  kafka:
#    consumer:
#      bootstrap-servers:
#    properties:
#      security.protocol: SSL
#    ssl:
#      trust-store-location:
#      trust-store-password:
