bootstrap.servers=pkc-lzoyy.europe-west6.gcp.confluent.cloud:9092
security.protocol=SASL_SSL
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='SQMK5BEA7NHXZ47Y' password='cfltoT71wK3a2KlLYgXzzAVPBa8RpSMik57CO7dmt9xIvpJ9nSSL2pYTrt+iLcPQ';
sasl.mechanism=PLAIN

key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

group.id=kafka-basic-cloud-consumer-group

topic=test-topic