auth:
  kafka:
    saslMechanism: SCRAM-SHA-512
    jksSecret: schemaregistry-truststore
    truststorePassword: verysecure

kafka:
  # we don't want Kafka broker to be started
  enabled: false

externalKafka:
  brokers:
    - SASL_SSL://my-cluster-kafka-bootstrap:9093
  listener:
    protocols: SASL_SSL
  sasl:
    user: schemaregistry
    password: NbVgy9nDScNDvMMGGbrKYnNtCaKB9ybM
