apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.2.1
    replicas: 1
    listeners:
      - name: plain
        port: 9095
        type: internal
        tls: false
      - name: external
        port: 9096
        type: nodeport
        tls: false
        configuration:
          preferredNodePortAddressType: Hostname
          bootstrap:
            nodePort: 30080
          brokers:
            - broker: 0
              nodePort: 30081
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: { }
    userOperator: { }
