apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  replicas: 3
  tls:
    secretRef: controller-tls
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dataVolumeCapacity: 1G
  image:
    application: docker.io/confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  replicas: 3
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  tls:
    secretRef: kafka-tls
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 1G
  tls:
    secretRef: controlcenter-tls
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic
  namespace: confluent
spec:
  kafkaRestClassRef:
    name: krc-cfk
  replicas: 3
  partitionCount: 4
  configs:
    cleanup.policy: "delete"