apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: demo-topic
  namespace: confluent
spec:
  replicas: 3
  partitionCount: 4
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  configs:
    cleanup.policy: "delete"