services:
  broker-1:
    image: apache/kafka:4.0.0
    container_name: broker-1
    environment:
      KAFKA_NODE_ID: 101
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-1:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@broker-1:9093,102@broker-2:9093,103@broker-3:9093
    volumes:
      - /var/lib/kafka/data
    networks:
      - kafka-net
    ports:
      - "19092:19092"

  broker-2:
    image: apache/kafka:4.0.0
    container_name: broker-2
    environment:
      KAFKA_NODE_ID: 102
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-2:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@broker-1:9093,102@broker-2:9093,103@broker-3:9093
    volumes:
      - /var/lib/kafka/data
    networks:
      - kafka-net
    ports:
      - "19093:19092"

  broker-3:
    image: apache/kafka:4.0.0
    container_name: broker-3
    environment:
      KAFKA_NODE_ID: 103
      CLUSTER_ID: ${CLUSTER_ID}
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-3:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 101@broker-1:9093,102@broker-2:9093,103@broker-3:9093
    volumes:
      - /var/lib/kafka/data
    networks:
      - kafka-net
    ports:
      - "19094:19092"

  kafdrop:
    image: obsidiandynamics/kafdrop:4.1.0
    networks:
      - kafka-net
    depends_on:
      - broker-1
      - broker-2
      - broker-3
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: broker-1:9092,broker-2:9092,broker-3:9092

networks:
  kafka-net:
