---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  dataVolumeCapacity: 2Gi
  storageClass:
    name: production-storage-class
  image:
    application: confluentinc/cp-enterprise-control-center:7.6.1
    init: confluentinc/confluent-init-container:2.8.0
