apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  replicas: 1
  dataVolumeCapacity: 2Gi
  storageClass:
    name: production-storage-class
  image:
    application: confluentinc/cp-server:7.6.1
    init: confluentinc/confluent-init-container:2.8.0
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  replicas: 3
  dataVolumeCapacity: 2Gi
  storageClass:
    name: production-storage-class
  metricReporter:
    enabled: true
  image:
    application: confluentinc/cp-server:7.6.1
    init: confluentinc/confluent-init-container:2.8.0
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
