apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: production-storage-class
# modify the provisioner for your environment
provisioner: rancher.io/local-path
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer