version: "3"
services:

  monitoring-demo:
    build: .
    container_name: monitoring-demo
    image: monitoring-demo:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus-config:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:10.4.4
    container_name: grafana
    restart: unless-stopped
    user: root
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./data/grafana:/var/lib/grafana