apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.2.3
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30080
          brokers:
            - broker: 0
              nodePort: 30081
              # modify it according to value `minikube ip`
              advertisedHost: 192.168.205.5
              advertisedPort: 8081
            - broker: 1
              nodePort: 30082
              # modify it according to value `minikube ip`
              advertisedHost: 192.168.205.5
              advertisedPort: 8082
            - broker: 2
              nodePort: 30083
              # modify it according to value `minikube ip`
              advertisedHost: 192.168.205.5
              advertisedPort: 8083
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: { }
    userOperator: { }
