---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3d-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3d-demo
  template:
    metadata:
      labels:
        app: k3d-demo
    spec:
      containers:
        - name: k3d-demo
          image: nginx
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: k3d-demo-internal
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: k3d-demo
---
apiVersion: v1
kind: Service
metadata:
  name: k3d-demo-external
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
      name: http
  selector:
    app: k3d-demo